version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./src:/usr/share/nginx/html/src
      - ./assets:/usr/share/nginx/html/assets
    environment:
      - NODE_ENV=development
    restart: unless-stopped